### ISSUE TITLE
도메인 설계 작업

### ISSUE THREAD

**Issue by hisonghyeon** [songhyeonpk/parking-management-Kotlin#14]
## 🍀 내용
- 도메인 별 엔티티, 컨트롤러, 서비스, 레포지토리 계층 설계
</br>
</br>

## ✅ TODO
- [x] 회원 도메인 설계
- [x] 주차장 도메인 설계
- [x] 주차이벤트 도메인 설계
