### ISSUE TITLE
Redis 설정 작업

### ISSUE THREAD

**Issue by hisonghyeon** [songhyeonpk/parking-management-Kotlin#18]
## 🍀 내용
- Redis 캐시 사용을 위해 Redis 설정 작업
</br>
</br>

## ✅ TODO
- [ ] redis dependency 추가
- [ ] redis config 파일을 추가하고 redis 서버 연동 및 캐시 설정
- [ ] redis 관련 설정 세팅
