### ISSUE TITLE
JWT 인증방식 설계

### ISSUE THREAD

**Issue by hisonghyeon** [songhyeonpk/parking-management-Kotlin#7]
## 🍀 내용
- 토큰 인증 방식 JWT 구현
</br>
</br>

## ✅ TODO
- [ ] JWT 설정 세팅
- [ ] 인증, 인가 관련 커스텀 에러코드, 예외 구현
- [ ] 토큰 인증 관련 기능 구현
- [ ] security JWT 설정 등록
